---
- hosts: localhost
  vars:
    api_key: "{{ lookup('file', '~/duffy.key') }}"
  tasks:
    - name: 'Get a new node'
      cico:
        action: get
        api_key: "{{ api_key }}"
      register: cico_data

    - name: 'Retry geting list of nodes'
      cico:
        action: list
        api_key: "{{ api_key }}"
        ssid: "{{ cico_data.results.ssid }}"
      register: cico_data
      when: len(cico_data.results.hosts) == 0

    - name: 'Fail if no hosts returned'
      fail:
        msg: 'Could not get hosts from ci.centos.org'
      when: len(cico_data.results.hosts) == 0

    - name: 'Write cico data locally'
      copy:
        content: "{{ cico_data.results | to_json }}"
        dest: "{{ playbook_dir }}/cico_data.json"

    - name: 'Write cico inventory'
      copy:
        content: |
          {% for host, value in cico_data.results.hosts.items() %}
          {{ value.hostname }} ansible_fqdn={{ value.hostname }} ansible_ssh_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_host={{ value.ip_address }}
          {% endfor %}
        dest: "{{ playbook_dir }}/cico_inventory"

    - name: 'Write cico ssh config file'
      template:
        src: templates/ssh_config.j2
        dest: "{{ playbook_dir }}/ssh_config"
